### PR TITLE
Fix markdown link syntax for FFI

### PR DESCRIPTION
**Pull request by kalouantonis**

### CODE REVIEW

**Comment by kalouantonis** [comment]
I've noticed this is the case for more areas of this wiki. 

I'll submit another PR to fix the rest after work :)

**Comment by pmetzger** [comment]
This isn't correct either, the right syntax is: `[description](url)`

Fix and push again?

**Comment by kalouantonis** [comment]
Oops, totally forgot. Sorry about that, i'll fix it now

**Comment by pmetzger** [comment]
Merged!

**Pull request merged**
