### PR TITLE
Add projects page to learning resources

### PR DESCRIPTION
**Pull request by kalouantonis**
Related to issue #13.

 I found a bunch of projects from all over the web, I think they're all decent quality code-wise.

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. Thank you, @kalouantonis!

**Comment by bluddy** [comment]
@kalouantonis I have a bit of an issue with this page in the sense that there's some overlap with the ecosystem. What's the difference between things that should be here vs in the ecosystem?

**Comment by bluddy** [comment]
I see. @kalouantonis would you agree with that description? In that case maybe this does belong in ecosystem and should be renamed to something like 'Mature Projects' or 'Successful Open Source Projects'? The file could still be projects. Then it could be linked to from learning. It still seems to me a bigger part of the ecosystem than learning.

Not a huge deal either way, I guess.

**Comment by kalouantonis** [comment]
I agree with @pmetzger's description. It was also for people that prefer to look at real world projects for learning purposes. I'm personally one of those people.

I do however think it makes more sense as a separate page in ecosystem rather than learning. That's where i'd be inclined to look and we can use that opportunity to remove some of the duplication between the new projects page and the stuff already on the ecosystem pages.

**Pull request merged**
